import type { Campaign, Category, Product } from "./types";

export const WHATSAPP_NUMBER = "5562999981746";
export const STORE_PHONE = "(62) 99998-1746";
export const SITE_URL = (process.env.NEXT_PUBLIC_SITE_URL || "https://ronymoveis.com").replace(/\/$/, "");
export const STORE_ADDRESS =
  "Av. C-12, 108 — Setor Sudoeste, Goiânia — GO, 74305-010";

export const seedCategories: Category[] = [
  {
    id: "cat-poltronas",
    slug: "poltronas",
    name: "Poltronas",
    description: "Conforto para receber, descansar e trabalhar melhor.",
    sortOrder: 1,
  },
  {
    id: "cat-cadeiras",
    slug: "cadeiras",
    name: "Cadeiras de escritório",
    description: "Modelos presidenciais, executivos, secretária e gamer.",
    sortOrder: 2,
  },
  {
    id: "cat-escritorio",
    slug: "escritorio",
    name: "Móveis para escritório",
    description: "Mesas, armários, estações e ambientes corporativos.",
    sortOrder: 3,
  },
  {
    id: "cat-planejados",
    slug: "planejados",
    name: "Móveis planejados",
    description: "Projetos sob medida para casa, escritório ou comércio.",
    sortOrder: 4,
  },
  {
    id: "cat-estofados",
    slug: "estofados",
    name: "Estofados",
    description: "Peças que combinam presença, acabamento e conforto.",
    sortOrder: 5,
  },
  {
    id: "cat-aco",
    slug: "moveis-de-aco",
    name: "Móveis de aço",
    description: "Organização resistente para arquivos e ambientes de trabalho.",
    sortOrder: 6,
  },
];

export const seedProducts: Product[] = [
  {
    id: "prod-atlanta",
    slug: "poltrona-atlanta-rivatti",
    name: "Poltrona Atlanta Rivatti",
    eyebrow: "Base excêntrica",
    shortDescription: "Curvas acolhedoras e giro suave para salas com personalidade.",
    description:
      "A Atlanta combina assento amplo, desenho contemporâneo e base excêntrica giratória. Uma peça de destaque para recepções, salas e espaços de leitura.",
    categoryId: "cat-poltronas",
    categorySlug: "poltronas",
    categoryName: "Poltronas",
    priceCents: 158000,
    oldPriceCents: 211949,
    priceLabel: null,
    badge: "Oferta",
    features: ["Base excêntrica giratória", "Design Rivatti", "Conforto envolvente"],
    images: ["/images/products/atlanta.webp"],
    active: true,
    featured: true,
    sortOrder: 1,
  },
  {
    id: "prod-melfi",
    slug: "poltrona-melfi-rivatti",
    name: "Poltrona Melfi Rivatti",
    eyebrow: "Base excêntrica",
    shortDescription: "Volume marcante, encosto alto e acabamento elegante.",
    description:
      "Com proporções generosas e base excêntrica, a Melfi foi feita para quem busca uma poltrona confortável sem abrir mão de um visual atual.",
    categoryId: "cat-poltronas",
    categorySlug: "poltronas",
    categoryName: "Poltronas",
    priceCents: 198000,
    oldPriceCents: 289900,
    priceLabel: null,
    badge: "Oferta",
    features: ["Base excêntrica", "Encosto alto", "Acabamento Rivatti"],
    images: ["/images/products/melfi.webp"],
    active: true,
    featured: true,
    sortOrder: 2,
  },
  {
    id: "prod-louisiana",
    slug: "poltrona-louisiana-massagem",
    name: "Poltrona Louisiana",
    eyebrow: "Reclinável com massagem",
    shortDescription: "Nove pontos de massagem e reclinação para desacelerar de verdade.",
    description:
      "A Louisiana entrega conforto completo com nove pontos de massagem e sistema reclinável. Ideal para criar uma pausa confortável em casa ou no escritório.",
    categoryId: "cat-poltronas",
    categorySlug: "poltronas",
    categoryName: "Poltronas",
    priceCents: 248000,
    oldPriceCents: 376300,
    priceLabel: null,
    badge: "Mais conforto",
    features: ["9 pontos de massagem", "Sistema reclinável", "Apoio para pernas"],
    images: ["/images/products/louisiana.webp"],
    active: true,
    featured: true,
    sortOrder: 3,
  },
  {
    id: "prod-elizabeth",
    slug: "poltrona-elizabeth-couro-natural",
    name: "Poltrona Elizabeth Rivatti",
    eyebrow: "Couro natural",
    shortDescription: "Couro natural e desenho clássico em uma presença sofisticada.",
    description:
      "A Elizabeth une o toque do couro natural a um desenho atemporal. Uma escolha elegante para salas, escritórios executivos e recepções.",
    categoryId: "cat-poltronas",
    categorySlug: "poltronas",
    categoryName: "Poltronas",
    priceCents: 298000,
    oldPriceCents: 380000,
    priceLabel: null,
    badge: "Couro natural",
    features: ["Couro natural", "Design Rivatti", "Acabamento premium"],
    images: ["/images/products/elizabeth.webp"],
    active: true,
    featured: false,
    sortOrder: 4,
  },
  {
    id: "prod-charles-eames",
    slug: "poltrona-charles-eames-rivatti",
    name: "Poltrona Charles Eames Rivatti",
    eyebrow: "Duas opções de revestimento",
    shortDescription: "Um clássico do design para compor salas e escritórios executivos.",
    description:
      "O desenho icônico da Charles Eames encontra duas opções de acabamento: couríssimo ou couro natural. Consulte as cores disponíveis na loja.",
    categoryId: "cat-poltronas",
    categorySlug: "poltronas",
    categoryName: "Poltronas",
    priceCents: 248000,
    oldPriceCents: 309000,
    priceLabel: "Couríssimo R$ 2.480 · couro natural R$ 3.480",
    badge: "2 revestimentos",
    features: ["Couríssimo ou couro natural", "Design clássico", "Base giratória"],
    images: ["/images/products/charles-eames.webp"],
    active: true,
    featured: false,
    sortOrder: 5,
  },
  {
    id: "prod-michigan",
    slug: "poltrona-michigan-massagem-eletrica",
    name: "Poltrona Michigan Rivatti",
    eyebrow: "Massagem elétrica",
    shortDescription: "Conforto elétrico, reclinação e presença para o seu espaço.",
    description:
      "A Michigan é uma poltrona robusta, reclinável e equipada com massagem elétrica. Pensada para quem deseja transformar descanso em experiência.",
    categoryId: "cat-poltronas",
    categorySlug: "poltronas",
    categoryName: "Poltronas",
    priceCents: 298000,
    oldPriceCents: 397000,
    priceLabel: null,
    badge: "Elétrica",
    features: ["Massagem elétrica", "Reclinável", "Conforto ampliado"],
    images: ["/images/products/michigan.webp"],
    active: true,
    featured: false,
    sortOrder: 6,
  },
  {
    id: "prod-home-office",
    slug: "home-office-planejado-nogueira",
    name: "Home office planejado Nogueira",
    eyebrow: "Projeto sob medida",
    shortDescription: "Marcenaria, organização e ergonomia desenhadas para a sua rotina.",
    description:
      "Planejamos cada centímetro do seu home office: bancada, armários, nichos, iluminação e acabamento. O projeto parte das suas medidas e necessidades.",
    categoryId: "cat-planejados",
    categorySlug: "planejados",
    categoryName: "Móveis planejados",
    priceCents: null,
    oldPriceCents: null,
    priceLabel: "Sob medida",
    badge: "Planejados",
    features: ["Projeto personalizado", "Escolha de acabamentos", "Aproveitamento do espaço"],
    images: ["/images/spaces/escritorio-planejado.webp", "/images/spaces/marcenaria-nogueira.webp"],
    active: true,
    featured: true,
    sortOrder: 7,
  },
  {
    id: "prod-cozinha-cobre",
    slug: "cozinha-planejada-cobre",
    name: "Cozinha planejada Cobre",
    eyebrow: "Projeto sob medida",
    shortDescription: "Linhas limpas, iluminação integrada e acabamento de presença.",
    description:
      "Uma proposta contemporânea que combina funcionalidade, marcenaria precisa e acabamento quente. Personalizamos medidas, ferragens e composição.",
    categoryId: "cat-planejados",
    categorySlug: "planejados",
    categoryName: "Móveis planejados",
    priceCents: null,
    oldPriceCents: null,
    priceLabel: "Solicite uma proposta",
    badge: "Projeto",
    features: ["Sob medida", "Ferragens selecionadas", "Iluminação integrada"],
    images: ["/images/spaces/cozinha-cobre.webp", "/images/spaces/cozinha-madeira.webp"],
    active: true,
    featured: true,
    sortOrder: 8,
  },
  {
    id: "prod-cadeiras-escritorio",
    slug: "cadeiras-para-escritorio",
    name: "Cadeiras para escritório",
    eyebrow: "Vários modelos",
    shortDescription: "Opções para recepção, operação, diretoria e home office.",
    description:
      "Encontre modelos presidente, executivo, diretor, secretária e gamer. Fale com a nossa equipe para escolher ergonomia, acabamento e faixa de valor.",
    categoryId: "cat-cadeiras",
    categorySlug: "cadeiras",
    categoryName: "Cadeiras de escritório",
    priceCents: null,
    oldPriceCents: null,
    priceLabel: "Consulte os modelos",
    badge: "Pronta entrega",
    features: ["Modelos ergonômicos", "Diversos acabamentos", "Atendimento na loja"],
    images: ["/images/spaces/cadeiras-escritorio.webp", "/images/spaces/mesa-escritorio.webp"],
    active: true,
    featured: false,
    sortOrder: 9,
  },
];

export const seedCampaign: Campaign = {
  id: "campaign-home",
  kind: "hero",
  eyebrow: "Móveis para viver e trabalhar melhor",
  title: "Seu espaço começa por uma boa escolha.",
  description:
    "Móveis para casa e escritório, cadeiras, estofados e projetos planejados — com atendimento próximo em Goiânia.",
  ctaLabel: "Explorar produtos",
  ctaHref: "/catalogo",
  imageUrl: "/images/spaces/escritorio-planejado.webp",
  active: true,
};

export function formatPrice(value: number | null) {
  if (value === null) return null;
  return new Intl.NumberFormat("pt-BR", {
    style: "currency",
    currency: "BRL",
  }).format(value / 100);
}
