import type { Campaign, Category, Product, SiteSettings } from "./types";

export const WHATSAPP_NUMBER = "5562999981746";
export const STORE_PHONE = "(62) 99998-1746";
export const SITE_URL = (process.env.NEXT_PUBLIC_SITE_URL || "https://ronymoveis.com").replace(/\/$/, "");
export const STORE_ADDRESS =
  "Av. C-12, 108 — Setor Sudoeste, Goiânia — GO, 74305-010";

export const DEFAULT_SITE_SETTINGS: SiteSettings = {
  businessName: "Rony Móveis",
  tagline: "Móveis para viver e trabalhar melhor.",
  announcement: "Atendimento em Goiânia · Casa, escritório e planejados",
  whatsappNumber: WHATSAPP_NUMBER,
  phone: STORE_PHONE,
  email: "ronymoveis12@gmail.com",
  instagramUrl: "https://www.instagram.com/ronymoveisgoiania/",
  address: STORE_ADDRESS,
  shortAddress: "Av. C-12, 108 · Setor Sudoeste · Goiânia",
  mapUrl: "https://maps.app.goo.gl/5Nz2rNHnaPNy8KGv9",
  openingHours: "Consulte o horário de atendimento pelo WhatsApp",
  seoTitle: "Rony Móveis | Casa, escritório e planejados em Goiânia",
  seoDescription: "Móveis para casa e escritório, cadeiras, poltronas, estofados e projetos planejados com atendimento em Goiânia.",
};

function category(
  input: Omit<Category, "parentName" | "active" | "featured" | "imageFit"> &
    Partial<Pick<Category, "parentName" | "active" | "featured" | "imageFit">>,
): Category {
  return {
    ...input,
    parentName: input.parentName ?? null,
    imageFit: input.imageFit ?? "cover",
    active: input.active ?? true,
    featured: input.featured ?? true,
  };
}

export const seedCategories: Category[] = [
  category({
    id: "cat-poltronas",
    slug: "poltronas",
    name: "Poltronas",
    description: "Conforto para receber, descansar e trabalhar melhor.",
    parentId: null,
    imageUrl: "/images/products/melfi.webp",
    imageFit: "contain",
    sortOrder: 1,
  }),
  category({
    id: "cat-cadeiras",
    slug: "cadeiras",
    name: "Cadeiras de escritório",
    description: "Modelos presidenciais, executivos, secretária e gamer.",
    parentId: null,
    imageUrl: "/images/rony-originals/carrossel-real-02.webp",
    imageFit: "contain",
    sortOrder: 2,
  }),
  category({
    id: "cat-escritorio",
    slug: "escritorio",
    name: "Móveis para escritório",
    description: "Mesas, armários, estações e ambientes corporativos.",
    parentId: null,
    imageUrl: "/images/rony-originals/carrossel-real-07.webp",
    sortOrder: 3,
  }),
  category({
    id: "cat-planejados",
    slug: "planejados",
    name: "Móveis planejados",
    description: "Projetos sob medida para casa, escritório ou comércio.",
    parentId: null,
    imageUrl: "/images/rony-originals/carrossel-real-08.webp",
    sortOrder: 4,
  }),
  category({
    id: "cat-estofados",
    slug: "estofados",
    name: "Estofados",
    description: "Peças que combinam presença, acabamento e conforto.",
    parentId: null,
    imageUrl: "/images/products/louisiana.webp",
    imageFit: "contain",
    sortOrder: 5,
  }),
  category({
    id: "cat-aco",
    slug: "moveis-de-aco",
    name: "Móveis de aço",
    description: "Organização resistente para arquivos e ambientes de trabalho.",
    parentId: null,
    imageUrl: "/images/rony-originals/home-produto-03.webp",
    imageFit: "contain",
    sortOrder: 6,
  }),
  category({ id: "cat-presidente", slug: "cadeiras-presidente", name: "Cadeiras Presidente", description: "Conforto, presença e apoio para jornadas mais longas.", parentId: "cat-cadeiras", imageUrl: "/images/legacy-chairs/presidente-01.webp", imageFit: "contain", sortOrder: 21 }),
  category({ id: "cat-executiva", slug: "cadeiras-executivas", name: "Cadeiras Executivas", description: "Ergonomia e acabamento para escritórios e home office.", parentId: "cat-cadeiras", imageUrl: "/images/legacy-chairs/executiva-01.webp", imageFit: "contain", sortOrder: 22 }),
  category({ id: "cat-diretor", slug: "cadeiras-diretor", name: "Cadeiras Diretor", description: "Modelos versáteis para estações, salas e escritórios.", parentId: "cat-cadeiras", imageUrl: "/images/legacy-chairs/diretor-01.webp", imageFit: "contain", sortOrder: 23 }),
  category({ id: "cat-secretaria", slug: "cadeiras-secretaria", name: "Cadeiras Secretária", description: "Opções funcionais para a rotina de trabalho.", parentId: "cat-cadeiras", imageUrl: "/images/legacy-chairs/secretaria-01.webp", imageFit: "contain", sortOrder: 24 }),
  category({ id: "cat-gamer", slug: "cadeiras-gamer", name: "Cadeiras Gamer", description: "Apoio e estilo para jogos, estudo e trabalho.", parentId: "cat-cadeiras", imageUrl: "/images/rony-originals/carrossel-real-04.webp", imageFit: "contain", sortOrder: 25 }),
  category({ id: "cat-banquetas", slug: "banquetas", name: "Banquetas", description: "Modelos para bancadas, cozinhas e ambientes comerciais.", parentId: "cat-cadeiras", imageUrl: "/images/rony-originals/carrossel-real-08.webp", sortOrder: 26 }),
];

const legacyChairGroups = [
  { key: "presidente", label: "Presidente", categoryId: "cat-presidente", categorySlug: "cadeiras-presidente", categoryName: "Cadeiras Presidente", count: 4, order: 110 },
  { key: "executiva", label: "Executiva", categoryId: "cat-executiva", categorySlug: "cadeiras-executivas", categoryName: "Cadeiras Executivas", count: 4, order: 120 },
  { key: "diretor", label: "Diretor", categoryId: "cat-diretor", categorySlug: "cadeiras-diretor", categoryName: "Cadeiras Diretor", count: 4, order: 130 },
  { key: "secretaria", label: "Secretária", categoryId: "cat-secretaria", categorySlug: "cadeiras-secretaria", categoryName: "Cadeiras Secretária", count: 3, order: 140 },
] as const;

const legacyChairProducts: Product[] = legacyChairGroups.flatMap((group) =>
  Array.from({ length: group.count }, (_, index) => {
    const number = String(index + 1).padStart(2, "0");
    return {
      id: `prod-cadeira-${group.key}-${number}`,
      slug: `cadeira-${group.key}-modelo-${number}`,
      name: `Cadeira ${group.label} — Modelo ${number}`,
      eyebrow: `${group.label} · consulte condições`,
      shortDescription: `Modelo da linha ${group.label.toLocaleLowerCase("pt-BR")} disponível para consulta na Rony Móveis.`,
      description: `Cadeira da linha ${group.label.toLocaleLowerCase("pt-BR")} apresentada no catálogo da Rony Móveis. Consulte a equipe para confirmar medidas, cores, revestimentos, recursos e disponibilidade atual.`,
      categoryId: group.categoryId,
      categorySlug: group.categorySlug,
      categoryName: group.categoryName,
      priceCents: null,
      oldPriceCents: null,
      priceLabel: "Preço sob consulta",
      priceMode: "consult" as const,
      availability: "available" as const,
      searchTerms: `cadeira escritório ${group.label.toLocaleLowerCase("pt-BR")} modelo ${number} goiânia`,
      badge: "Consulte",
      features: ["Preço sob consulta", "Consulte cores e acabamentos", "Confirme a disponibilidade"],
      images: [`/images/legacy-chairs/${group.key}-${number}.webp`],
      active: true,
      featured: false,
      sortOrder: group.order + index,
    };
  }),
);

export const seedProducts: Product[] = [
  {
    id: "prod-atlanta",
    slug: "poltrona-atlanta-rivatti",
    name: "Poltrona Atlanta Rivatti",
    eyebrow: "Base excêntrica",
    shortDescription: "Curvas acolhedoras e giro suave para salas com personalidade.",
    description:
      "A Atlanta combina assento amplo, desenho contemporâneo e base excêntrica giratória. Uma peça de destaque para recepções, salas e espaços de leitura.",
    categoryId: "cat-poltronas",
    categorySlug: "poltronas",
    categoryName: "Poltronas",
    priceCents: 158000,
    oldPriceCents: 211949,
    priceLabel: null,
    priceMode: "price",
    availability: "available",
    searchTerms: "poltrona giratória sala recepção base excêntrica rivatti",
    badge: "Oferta",
    features: ["Base excêntrica giratória", "Design Rivatti", "Conforto envolvente"],
    images: ["/images/products/atlanta.webp"],
    active: true,
    featured: true,
    sortOrder: 1,
  },
  {
    id: "prod-melfi",
    slug: "poltrona-melfi-rivatti",
    name: "Poltrona Melfi Rivatti",
    eyebrow: "Base excêntrica",
    shortDescription: "Volume marcante, encosto alto e acabamento elegante.",
    description:
      "Com proporções generosas e base excêntrica, a Melfi foi feita para quem busca uma poltrona confortável sem abrir mão de um visual atual.",
    categoryId: "cat-poltronas",
    categorySlug: "poltronas",
    categoryName: "Poltronas",
    priceCents: 198000,
    oldPriceCents: 289900,
    priceLabel: null,
    priceMode: "price",
    availability: "available",
    searchTerms: "poltrona giratória encosto alto base excêntrica rivatti",
    badge: "Oferta",
    features: ["Base excêntrica", "Encosto alto", "Acabamento Rivatti"],
    images: ["/images/products/melfi.webp"],
    active: true,
    featured: true,
    sortOrder: 2,
  },
  {
    id: "prod-louisiana",
    slug: "poltrona-louisiana-massagem",
    name: "Poltrona Louisiana",
    eyebrow: "Reclinável com massagem",
    shortDescription: "Nove pontos de massagem e reclinação para desacelerar de verdade.",
    description:
      "A Louisiana entrega conforto completo com nove pontos de massagem e sistema reclinável. Ideal para criar uma pausa confortável em casa ou no escritório.",
    categoryId: "cat-poltronas",
    categorySlug: "poltronas",
    categoryName: "Poltronas",
    priceCents: 248000,
    oldPriceCents: 376300,
    priceLabel: null,
    priceMode: "price",
    availability: "available",
    searchTerms: "poltrona reclinável massagem descanso nove pontos",
    badge: "Mais conforto",
    features: ["9 pontos de massagem", "Sistema reclinável", "Apoio para pernas"],
    images: ["/images/products/louisiana.webp"],
    active: true,
    featured: true,
    sortOrder: 3,
  },
  {
    id: "prod-elizabeth",
    slug: "poltrona-elizabeth-couro-natural",
    name: "Poltrona Elizabeth Rivatti",
    eyebrow: "Couro natural",
    shortDescription: "Couro natural e desenho clássico em uma presença sofisticada.",
    description:
      "A Elizabeth une o toque do couro natural a um desenho atemporal. Uma escolha elegante para salas, escritórios executivos e recepções.",
    categoryId: "cat-poltronas",
    categorySlug: "poltronas",
    categoryName: "Poltronas",
    priceCents: 298000,
    oldPriceCents: 380000,
    priceLabel: null,
    priceMode: "price",
    availability: "available",
    searchTerms: "poltrona couro natural clássica executiva recepção rivatti",
    badge: "Couro natural",
    features: ["Couro natural", "Design Rivatti", "Acabamento premium"],
    images: ["/images/products/elizabeth.webp"],
    active: true,
    featured: false,
    sortOrder: 4,
  },
  {
    id: "prod-charles-eames",
    slug: "poltrona-charles-eames-rivatti",
    name: "Poltrona Charles Eames Rivatti",
    eyebrow: "Duas opções de revestimento",
    shortDescription: "Um clássico do design para compor salas e escritórios executivos.",
    description:
      "O desenho icônico da Charles Eames encontra duas opções de acabamento: couríssimo ou couro natural. Consulte as cores disponíveis na loja.",
    categoryId: "cat-poltronas",
    categorySlug: "poltronas",
    categoryName: "Poltronas",
    priceCents: 248000,
    oldPriceCents: 309000,
    priceLabel: "Couríssimo R$ 2.480 · couro natural R$ 3.480",
    priceMode: "from",
    availability: "available",
    searchTerms: "charles eames couro natural couríssimo design clássico rivatti",
    badge: "2 revestimentos",
    features: ["Couríssimo ou couro natural", "Design clássico", "Base giratória"],
    images: ["/images/products/charles-eames.webp"],
    active: true,
    featured: false,
    sortOrder: 5,
  },
  {
    id: "prod-michigan",
    slug: "poltrona-michigan-massagem-eletrica",
    name: "Poltrona Michigan Rivatti",
    eyebrow: "Massagem elétrica",
    shortDescription: "Conforto elétrico, reclinação e presença para o seu espaço.",
    description:
      "A Michigan é uma poltrona robusta, reclinável e equipada com massagem elétrica. Pensada para quem deseja transformar descanso em experiência.",
    categoryId: "cat-poltronas",
    categorySlug: "poltronas",
    categoryName: "Poltronas",
    priceCents: 298000,
    oldPriceCents: 397000,
    priceLabel: null,
    priceMode: "price",
    availability: "available",
    searchTerms: "poltrona massagem elétrica reclinável descanso rivatti",
    badge: "Elétrica",
    features: ["Massagem elétrica", "Reclinável", "Conforto ampliado"],
    images: ["/images/products/michigan.webp"],
    active: true,
    featured: false,
    sortOrder: 6,
  },
  {
    id: "prod-home-office",
    slug: "home-office-planejado-nogueira",
    name: "Home office planejado Nogueira",
    eyebrow: "Projeto sob medida",
    shortDescription: "Marcenaria, organização e ergonomia desenhadas para a sua rotina.",
    description:
      "Planejamos cada centímetro do seu home office: bancada, armários, nichos, iluminação e acabamento. O projeto parte das suas medidas e necessidades.",
    categoryId: "cat-planejados",
    categorySlug: "planejados",
    categoryName: "Móveis planejados",
    priceCents: null,
    oldPriceCents: null,
    priceLabel: "Sob medida",
    priceMode: "custom",
    availability: "made_to_order",
    searchTerms: "home office planejado marcenaria bancada armário escritório",
    badge: "Planejados",
    features: ["Projeto personalizado", "Escolha de acabamentos", "Aproveitamento do espaço"],
    images: ["/images/rony-originals/carrossel-real-07.webp", "/images/rony-originals/carrossel-real-06.webp"],
    active: true,
    featured: true,
    sortOrder: 7,
  },
  {
    id: "prod-cozinha-cobre",
    slug: "cozinha-planejada-cobre",
    name: "Cozinha planejada Cobre",
    eyebrow: "Projeto sob medida",
    shortDescription: "Linhas limpas, iluminação integrada e acabamento de presença.",
    description:
      "Uma proposta contemporânea que combina funcionalidade, marcenaria precisa e acabamento quente. Personalizamos medidas, ferragens e composição.",
    categoryId: "cat-planejados",
    categorySlug: "planejados",
    categoryName: "Móveis planejados",
    priceCents: null,
    oldPriceCents: null,
    priceLabel: "Solicite uma proposta",
    priceMode: "custom",
    availability: "made_to_order",
    searchTerms: "cozinha planejada marcenaria sob medida armários ferragens",
    badge: "Projeto",
    features: ["Sob medida", "Ferragens selecionadas", "Iluminação integrada"],
    images: ["/images/rony-originals/carrossel-real-08.webp"],
    active: true,
    featured: true,
    sortOrder: 8,
  },
  {
    id: "prod-cadeiras-escritorio",
    slug: "cadeiras-para-escritorio",
    name: "Cadeiras para escritório",
    eyebrow: "Vários modelos",
    shortDescription: "Opções para recepção, operação, diretoria e home office.",
    description:
      "Encontre modelos presidente, executivo, diretor, secretária e gamer. Fale com a nossa equipe para escolher ergonomia, acabamento e faixa de valor.",
    categoryId: "cat-cadeiras",
    categorySlug: "cadeiras",
    categoryName: "Cadeiras de escritório",
    priceCents: null,
    oldPriceCents: null,
    priceLabel: "Consulte os modelos",
    priceMode: "consult",
    availability: "available",
    searchTerms: "cadeira presidente executiva diretor secretária gamer home office ergonomia",
    badge: "Pronta entrega",
    features: ["Modelos ergonômicos", "Diversos acabamentos", "Atendimento na loja"],
    images: ["/images/rony-originals/carrossel-real-02.webp", "/images/rony-originals/carrossel-real-01.webp"],
    active: true,
    featured: false,
    sortOrder: 9,
  },
  {
    id: "prod-florenca-alta",
    slug: "cadeira-florenca-alta-rodizio-preta",
    name: "Cadeira Florença Alta Rodízio Preta",
    eyebrow: "Linha presidente",
    shortDescription: "Encosto alto, braços cromados e presença para o escritório.",
    description: "Modelo Florença com encosto alto e rodízios, apresentado no catálogo da Rony Móveis. Consulte medidas, regulagens e disponibilidade atual.",
    categoryId: "cat-presidente",
    categorySlug: "cadeiras-presidente",
    categoryName: "Cadeiras Presidente",
    priceCents: null,
    oldPriceCents: null,
    priceLabel: "Preço sob consulta",
    priceMode: "consult",
    availability: "available",
    searchTerms: "cadeira florenca florença alta rodizio rodízio preta presidente escritorio",
    badge: "Catálogo da loja",
    features: ["Encosto alto", "Base com rodízios", "Consulte regulagens e medidas"],
    images: ["/images/rony-originals/home-produto-01.webp"],
    active: true,
    featured: false,
    sortOrder: 100,
  },
  {
    id: "prod-cadeira-addit",
    slug: "cadeira-addit",
    name: "Cadeira Addit",
    eyebrow: "Linha executiva",
    shortDescription: "Encosto em tela, braços reguláveis e visual contemporâneo.",
    description: "Cadeira Addit apresentada no catálogo da Rony Móveis. Fale com a equipe para confirmar cores, medidas, regulagens e disponibilidade.",
    categoryId: "cat-executiva",
    categorySlug: "cadeiras-executivas",
    categoryName: "Cadeiras Executivas",
    priceCents: null,
    oldPriceCents: null,
    priceLabel: "Preço sob consulta",
    priceMode: "consult",
    availability: "available",
    searchTerms: "cadeira addit tela executiva escritorio ergonomica",
    badge: "Catálogo da loja",
    features: ["Encosto em tela", "Base com rodízios", "Consulte cores e regulagens"],
    images: ["/images/rony-originals/home-produto-02.webp"],
    active: true,
    featured: false,
    sortOrder: 101,
  },
  {
    id: "prod-martiflex-longarina",
    slug: "martiflex-longarina-executiva",
    name: "Martiflex Longarina Executiva",
    eyebrow: "Recepção e espera",
    shortDescription: "Três lugares para recepções, corredores e áreas de espera.",
    description: "Longarina executiva Martiflex com três assentos, apresentada no catálogo da Rony Móveis. Consulte medidas, acabamento e disponibilidade.",
    categoryId: "cat-escritorio",
    categorySlug: "escritorio",
    categoryName: "Móveis para escritório",
    priceCents: null,
    oldPriceCents: null,
    priceLabel: "Preço sob consulta",
    priceMode: "consult",
    availability: "available",
    searchTerms: "martiflex longarina executiva tres lugares recepcao espera escritorio",
    badge: "Catálogo da loja",
    features: ["Três lugares", "Uso corporativo", "Consulte medidas e acabamento"],
    images: ["/images/rony-originals/home-produto-03.webp"],
    active: true,
    featured: false,
    sortOrder: 102,
  },
  {
    id: "prod-executiva-fixa-office",
    slug: "cadeira-executiva-base-fixa-office-gomada",
    name: "Cadeira Executiva Base Fixa Office Gomada",
    eyebrow: "Base fixa",
    shortDescription: "Assento e encosto gomados para atendimento e reunião.",
    description: "Cadeira executiva da linha Office com base fixa, apresentada no catálogo da Rony Móveis. Consulte cores, medidas e disponibilidade.",
    categoryId: "cat-executiva",
    categorySlug: "cadeiras-executivas",
    categoryName: "Cadeiras Executivas",
    priceCents: null,
    oldPriceCents: null,
    priceLabel: "Preço sob consulta",
    priceMode: "consult",
    availability: "available",
    searchTerms: "cadeira executiva base fixa office gomada reuniao atendimento",
    badge: "Catálogo da loja",
    features: ["Base fixa", "Assento e encosto gomados", "Consulte cores disponíveis"],
    images: ["/images/rony-originals/home-produto-04.webp"],
    active: true,
    featured: false,
    sortOrder: 103,
  },
  ...legacyChairProducts,
];

export const seedCampaign: Campaign = {
  id: "campaign-home",
  kind: "hero",
  eyebrow: "Móveis para viver e trabalhar melhor",
  title: "Seu espaço começa por uma boa escolha.",
  description:
    "Móveis para casa e escritório, cadeiras, estofados e projetos planejados — com atendimento próximo em Goiânia.",
  ctaLabel: "Explorar produtos",
  ctaHref: "/catalogo",
  imageUrl: "/images/rony-originals/carrossel-real-05.webp",
  active: true,
};

export function formatPrice(value: number | null) {
  if (value === null) return null;
  return new Intl.NumberFormat("pt-BR", {
    style: "currency",
    currency: "BRL",
  }).format(value / 100);
}

export const AVAILABILITY_LABELS: Record<Product["availability"], string> = {
  available: "Disponível",
  order: "Por encomenda",
  made_to_order: "Produção sob medida",
  out_of_stock: "Indisponível por enquanto",
};

export function productPriceText(product: Pick<Product, "priceCents" | "priceLabel" | "priceMode">) {
  const price = formatPrice(product.priceCents);
  if (product.priceMode === "from" && price) return `A partir de ${price}`;
  if (product.priceMode === "consult") return product.priceLabel || "Preço sob consulta";
  if (product.priceMode === "custom") return product.priceLabel || "Solicite uma proposta";
  return price || product.priceLabel || "Preço sob consulta";
}
