import type { Product } from "./types";

const imageRoot = "/images/cadeiras-setembro-2026";

const categories = {
  "cat-presidente": { slug: "cadeiras-presidente", name: "Cadeiras Presidente" },
  "cat-executiva": { slug: "cadeiras-executivas", name: "Cadeiras Executivas" },
  "cat-diretor": { slug: "cadeiras-diretor", name: "Cadeiras Diretor" },
  "cat-secretaria": { slug: "cadeiras-secretaria", name: "Cadeiras Secretária" },
  "cat-escritorio": { slug: "escritorio", name: "Móveis para escritório" },
} as const;

type ChairInput = {
  id: string;
  slug: string;
  name: string;
  eyebrow: string;
  shortDescription: string;
  description: string;
  categoryId: keyof typeof categories;
  searchTerms: string;
  features: string[];
  images: string[];
  sortOrder: number;
};

function chair(input: ChairInput): Product {
  const category = categories[input.categoryId];
  return {
    ...input,
    categorySlug: category.slug,
    categoryName: category.name,
    priceCents: null,
    oldPriceCents: null,
    priceLabel: "Preço sob consulta",
    priceMode: "consult",
    availability: "available",
    badge: "Consulte",
    active: true,
    featured: false,
  };
}

export const september2026ChairProducts: Product[] = [
  chair({
    id: "prod-set26-secretaria-giratoria-verde",
    slug: "cadeira-secretaria-giratoria-verde",
    name: "Cadeira Secretária Giratória Verde",
    eyebrow: "Compacta e funcional",
    shortDescription: "Modelo giratório sem braços, indicado para postos operacionais e home office.",
    description: "Cadeira secretária com assento e encosto estofados, regulagem de altura e base giratória com rodízios. Consulte a equipe para confirmar tecido, medidas e disponibilidade.",
    categoryId: "cat-secretaria",
    searchTerms: "cadeira secretária secretaria giratória verde sem braços operacional home office",
    features: ["Base giratória com rodízios", "Regulagem de altura", "Modelo sem braços"],
    images: [`${imageRoot}/secretaria-giratoria-verde.webp`],
    sortOrder: 201,
  }),
  chair({
    id: "prod-set26-secretaria-fixa-azul",
    slug: "cadeira-secretaria-fixa-azul",
    name: "Cadeira Secretária Fixa Azul",
    eyebrow: "Base quatro pés",
    shortDescription: "Opção compacta para atendimento, reunião, treinamento e recepção.",
    description: "Cadeira secretária fixa com assento e encosto estofados e estrutura metálica de quatro pés. Consulte cores, revestimentos, medidas e disponibilidade atual.",
    categoryId: "cat-secretaria",
    searchTerms: "cadeira secretária secretaria fixa azul quatro pés atendimento reunião treinamento",
    features: ["Base fixa de quatro pés", "Assento e encosto estofados", "Formato compacto"],
    images: [`${imageRoot}/secretaria-fixa-azul.webp`],
    sortOrder: 202,
  }),
  chair({
    id: "prod-set26-strike-fixa",
    slug: "cadeira-strike-fixa-preta",
    name: "Cadeira Strike Fixa Preta",
    eyebrow: "Uso coletivo",
    shortDescription: "Cadeira leve em polipropileno para ambientes de espera, treinamento e eventos.",
    description: "Modelo Strike fixo, com assento e encosto em polipropileno e estrutura metálica. Uma solução prática para espaços de uso coletivo. Consulte medidas e disponibilidade.",
    categoryId: "cat-secretaria",
    searchTerms: "cadeira strike fixa preta polipropileno empilhável treinamento espera evento",
    features: ["Assento e encosto em polipropileno", "Estrutura metálica", "Uso versátil"],
    images: [`${imageRoot}/strike-fixa.webp`],
    sortOrder: 203,
  }),
  chair({
    id: "prod-set26-diretor-tela-cinza",
    slug: "cadeira-diretor-tela-cinza-base-cromada",
    name: "Cadeira Diretor em Tela Cinza",
    eyebrow: "Base cromada",
    shortDescription: "Encosto alto em tela e acabamento cromado para escritórios contemporâneos.",
    description: "Cadeira diretor giratória com encosto alto em tela, assento estofado, braços e base cromada com rodízios. Consulte regulagens, medidas e disponibilidade.",
    categoryId: "cat-diretor",
    searchTerms: "cadeira diretor tela mesh cinza base cromada rodízios escritório",
    features: ["Encosto alto em tela", "Base cromada com rodízios", "Apoio para os braços"],
    images: [`${imageRoot}/diretor-tela-cinza.webp`],
    sortOrder: 204,
  }),
  chair({
    id: "prod-set26-diretor-matelasse-preta",
    slug: "cadeira-diretor-matelasse-preta",
    name: "Cadeira Diretor Matelassê Preta",
    eyebrow: "Acabamento geométrico",
    shortDescription: "Assento e encosto com costura matelassê para salas e postos de trabalho.",
    description: "Cadeira diretor giratória com braços, assento e encosto estofados com costura matelassê. Consulte a equipe para confirmar revestimento, regulagens e disponibilidade.",
    categoryId: "cat-diretor",
    searchTerms: "cadeira diretor matelassê matelasse preta costura losango escritório",
    features: ["Costura matelassê", "Base giratória com rodízios", "Apoio para os braços"],
    images: [`${imageRoot}/diretor-matelasse-preta.webp`],
    sortOrder: 205,
  }),
  chair({
    id: "prod-set26-diretor-matelasse-marrom",
    slug: "cadeira-diretor-matelasse-marrom",
    name: "Cadeira Diretor Matelassê Marrom",
    eyebrow: "Tom marrom",
    shortDescription: "Modelo giratório com braços e costura geométrica no assento e encosto.",
    description: "Cadeira diretor em tom marrom, com assento e encosto estofados em padrão matelassê, braços e base giratória com rodízios. Consulte detalhes e disponibilidade.",
    categoryId: "cat-diretor",
    searchTerms: "cadeira diretor matelassê matelasse marrom costura losango escritório",
    features: ["Revestimento em tom marrom", "Costura matelassê", "Base giratória com rodízios"],
    images: [`${imageRoot}/diretor-matelasse-marrom.webp`],
    sortOrder: 206,
  }),
  chair({
    id: "prod-set26-caixa-executiva-aro",
    slug: "cadeira-caixa-executiva-com-aro",
    name: "Cadeira Caixa Executiva com Aro",
    eyebrow: "Para bancadas altas",
    shortDescription: "Assento estofado, encosto e aro para apoio dos pés em postos elevados.",
    description: "Cadeira caixa executiva com assento e encosto estofados, regulagem de altura e aro para apoio dos pés. Indicada para balcões, caixas e bancadas altas.",
    categoryId: "cat-executiva",
    searchTerms: "cadeira caixa executiva aro apoio pés bancada balcão alta",
    features: ["Aro para apoio dos pés", "Regulagem de altura", "Assento e encosto estofados"],
    images: [`${imageRoot}/caixa-executiva-aro.webp`],
    sortOrder: 207,
  }),
  chair({
    id: "prod-set26-presidente-tela-cinza",
    slug: "cadeira-presidente-tela-cinza",
    name: "Cadeira Presidente em Tela Cinza",
    eyebrow: "Apoio de cabeça",
    shortDescription: "Encosto alto em tela, apoio de cabeça e base cromada para jornadas prolongadas.",
    description: "Cadeira presidente com encosto alto em tela, apoio de cabeça, braços, assento estofado e base cromada com rodízios. Consulte regulagens e disponibilidade.",
    categoryId: "cat-presidente",
    searchTerms: "cadeira presidente tela mesh cinza apoio cabeça base cromada escritório",
    features: ["Encosto alto em tela", "Apoio de cabeça", "Base cromada com rodízios"],
    images: [`${imageRoot}/presidente-tela-cinza.webp`],
    sortOrder: 208,
  }),
  chair({
    id: "prod-set26-presidente-tela-alta-cromada",
    slug: "cadeira-presidente-tela-alta-cromada",
    name: "Cadeira Presidente Tela Alta Cromada",
    eyebrow: "Visual leve",
    shortDescription: "Encosto alto em tela com estrutura e base cromadas.",
    description: "Cadeira presidente giratória com encosto alto em tela, braços integrados, assento estofado e base cromada com rodízios. Consulte medidas, regulagens e disponibilidade.",
    categoryId: "cat-presidente",
    searchTerms: "cadeira presidente tela alta mesh cromada braços rodízios",
    features: ["Encosto alto em tela", "Estrutura cromada", "Base giratória com rodízios"],
    images: [`${imageRoot}/presidente-tela-alta-cromada.webp`],
    sortOrder: 209,
  }),
  chair({
    id: "prod-set26-ergonomica-apoio-cabeca",
    slug: "cadeira-ergonomica-tela-apoio-cabeca",
    name: "Cadeira Ergonômica em Tela com Apoio de Cabeça",
    eyebrow: "Apoios ajustáveis",
    shortDescription: "Tela respirável, apoio de cabeça e braços para uma postura mais confortável.",
    description: "Cadeira ergonômica giratória com encosto em tela, apoio de cabeça, suporte lombar, braços e base com rodízios. Consulte as regulagens disponíveis neste modelo.",
    categoryId: "cat-presidente",
    searchTerms: "cadeira ergonômica ergonomica tela apoio cabeça lombar braços reguláveis",
    features: ["Encosto em tela", "Apoio de cabeça", "Suporte lombar"],
    images: [`${imageRoot}/ergonomica-apoio-cabeca.webp`],
    sortOrder: 210,
  }),
  chair({
    id: "prod-set26-diretor-tela-base-fixa",
    slug: "cadeira-diretor-tela-base-fixa",
    name: "Cadeira Diretor em Tela Base Fixa",
    eyebrow: "Base contínua",
    shortDescription: "Encosto em tela e base fixa para reunião, atendimento e aproximação.",
    description: "Cadeira diretor fixa com encosto em tela, assento estofado, braços integrados e base metálica contínua. Consulte medidas e disponibilidade.",
    categoryId: "cat-diretor",
    searchTerms: "cadeira diretor tela mesh base fixa contínua reunião atendimento aproximação",
    features: ["Encosto em tela", "Base fixa contínua", "Apoio para os braços"],
    images: [`${imageRoot}/diretor-tela-base-fixa.webp`],
    sortOrder: 211,
  }),
  chair({
    id: "prod-set26-presidente-matelasse",
    slug: "cadeira-presidente-matelasse-preta",
    name: "Cadeira Presidente Matelassê Preta",
    eyebrow: "Encosto alto",
    shortDescription: "Estofamento com costura matelassê e braços para um escritório de presença.",
    description: "Cadeira presidente com encosto alto, assento e encosto estofados em padrão matelassê, braços e base giratória com rodízios. Consulte regulagens e revestimento.",
    categoryId: "cat-presidente",
    searchTerms: "cadeira presidente matelassê matelasse preta encosto alto costura losango",
    features: ["Encosto alto estofado", "Costura matelassê", "Base giratória com rodízios"],
    images: [`${imageRoot}/presidente-matelasse.webp`],
    sortOrder: 212,
  }),
  chair({
    id: "prod-set26-executiva-estofada-bracos",
    slug: "cadeira-executiva-estofada-com-bracos",
    name: "Cadeira Executiva Estofada com Braços",
    eyebrow: "Uso operacional",
    shortDescription: "Assento e encosto estofados com braços para a rotina de trabalho.",
    description: "Cadeira executiva giratória com assento e encosto estofados, braços e base com rodízios. Consulte cores, medidas, regulagens e disponibilidade atual.",
    categoryId: "cat-executiva",
    searchTerms: "cadeira executiva estofada braços giratória operacional escritório",
    features: ["Assento e encosto estofados", "Apoio para os braços", "Base giratória com rodízios"],
    images: [`${imageRoot}/executiva-estofada-bracos.webp`],
    sortOrder: 213,
  }),
  chair({
    id: "prod-set26-caixa-secretaria-aro",
    slug: "cadeira-caixa-secretaria-com-aro",
    name: "Cadeira Caixa Secretária com Aro",
    eyebrow: "Compacta para balcões",
    shortDescription: "Modelo sem braços com aro para apoio dos pés e base giratória.",
    description: "Cadeira caixa da linha secretária, com assento e encosto estofados, regulagem de altura, aro para apoio dos pés e base com sapatas. Consulte medidas e disponibilidade.",
    categoryId: "cat-secretaria",
    searchTerms: "cadeira caixa secretária secretaria aro apoio pés balcão bancada",
    features: ["Aro para apoio dos pés", "Regulagem de altura", "Modelo sem braços"],
    images: [`${imageRoot}/caixa-secretaria-aro.webp`],
    sortOrder: 214,
  }),
  chair({
    id: "prod-set26-executiva-back-system",
    slug: "cadeira-executiva-back-system",
    name: "Cadeira Executiva Back System",
    eyebrow: "Apoio para a rotina",
    shortDescription: "Modelo giratório com braços e encosto estofado de desenho anatômico.",
    description: "Cadeira executiva giratória com assento e encosto estofados, braços e base com rodízios. Consulte a equipe para confirmar mecanismo, regulagens e disponibilidade.",
    categoryId: "cat-executiva",
    searchTerms: "cadeira executiva back system ergonômica estofada braços escritório",
    features: ["Encosto estofado anatômico", "Apoio para os braços", "Base giratória com rodízios"],
    images: [`${imageRoot}/executiva-back-system.webp`],
    sortOrder: 215,
  }),
  chair({
    id: "prod-set26-ergonomica-encosto-articulado",
    slug: "cadeira-ergonomica-nr17-encosto-articulado",
    name: "Cadeira Ergonômica NR17 com Encosto Articulado",
    eyebrow: "Suporte dividido",
    shortDescription: "Encosto articulado em duas partes para acompanhar melhor a região das costas.",
    description: "Cadeira ergonômica com encosto articulado, assento estofado, braços e base giratória com rodízios. Consulte ajustes, certificação do lote e disponibilidade.",
    categoryId: "cat-executiva",
    searchTerms: "cadeira ergonômica ergonomica nr17 encosto articulado dividido escritório",
    features: ["Encosto articulado em duas partes", "Apoio para os braços", "Base giratória com rodízios"],
    images: [`${imageRoot}/ergonomica-encosto-articulado.webp`],
    sortOrder: 216,
  }),
  chair({
    id: "prod-set26-presidente-matelasse-cinza",
    slug: "cadeira-presidente-matelasse-cinza",
    name: "Cadeira Presidente Matelassê Cinza",
    eyebrow: "Encosto alto estofado",
    shortDescription: "Estofamento cinza com costura geométrica para escritórios e salas executivas.",
    description: "Cadeira presidente com encosto alto, braços, estofamento cinza em padrão matelassê e base giratória com rodízios. Consulte revestimento e regulagens.",
    categoryId: "cat-presidente",
    searchTerms: "cadeira presidente matelassê matelasse cinza encosto alto escritório",
    features: ["Estofamento em tom cinza", "Costura matelassê", "Base giratória com rodízios"],
    images: [`${imageRoot}/presidente-matelasse-cinza.webp`],
    sortOrder: 217,
  }),
  chair({
    id: "prod-set26-iso-fixa-plastica",
    slug: "cadeira-iso-fixa-plastica-preta",
    name: "Cadeira ISO Fixa Plástica Preta",
    eyebrow: "Prática e leve",
    shortDescription: "Modelo plástico de quatro pés para espera, treinamento e uso coletivo.",
    description: "Cadeira ISO fixa com assento e encosto plásticos e estrutura metálica de quatro pés. Consulte capacidade, medidas e disponibilidade.",
    categoryId: "cat-secretaria",
    searchTerms: "cadeira iso fixa plástica preta quatro pés treinamento espera coletiva",
    features: ["Assento e encosto plásticos", "Estrutura metálica", "Base fixa de quatro pés"],
    images: [`${imageRoot}/iso-fixa-plastica.webp`],
    sortOrder: 218,
  }),
  chair({
    id: "prod-set26-diretor-matelasse-cromada",
    slug: "cadeira-diretor-matelasse-base-cromada",
    name: "Cadeira Diretor Matelassê Base Cromada",
    eyebrow: "Acabamento cromado",
    shortDescription: "Costura geométrica, braços e base cromada para ambientes profissionais.",
    description: "Cadeira diretor giratória com assento e encosto estofados em padrão matelassê, braços e base cromada com rodízios. Consulte regulagens e disponibilidade.",
    categoryId: "cat-diretor",
    searchTerms: "cadeira diretor matelassê matelasse base cromada braços escritório",
    features: ["Costura matelassê", "Base cromada com rodízios", "Apoio para os braços"],
    images: [`${imageRoot}/diretor-matelasse-cromada.webp`],
    sortOrder: 219,
  }),
  chair({
    id: "prod-set26-presidente-estofada-gomos",
    slug: "cadeira-presidente-estofada-gomos",
    name: "Cadeira Presidente Estofada com Gomos",
    eyebrow: "Conforto envolvente",
    shortDescription: "Encosto alto com estofamento segmentado para salas executivas.",
    description: "Cadeira presidente com encosto alto e estofamento em gomos, braços e base giratória com rodízios. Consulte revestimento, regulagens e disponibilidade.",
    categoryId: "cat-presidente",
    searchTerms: "cadeira presidente estofada gomos encosto alto executiva escritório",
    features: ["Encosto alto em gomos", "Assento estofado", "Base giratória com rodízios"],
    images: [`${imageRoot}/presidente-estofada-gomos.webp`],
    sortOrder: 220,
  }),
  chair({
    id: "prod-set26-longarina-secretaria",
    slug: "longarina-secretaria-tres-lugares-base-preta",
    name: "Longarina Secretária 3 Lugares Base Preta",
    eyebrow: "Recepção e espera",
    shortDescription: "Três assentos estofados em uma estrutura metálica de base preta.",
    description: "Longarina secretária de três lugares com assentos e encostos estofados e estrutura metálica preta. Indicada para recepções, clínicas e áreas de espera.",
    categoryId: "cat-escritorio",
    searchTerms: "longarina secretária secretaria três 3 lugares estofada recepção espera base preta",
    features: ["Três lugares", "Assentos e encostos estofados", "Estrutura metálica preta"],
    images: [`${imageRoot}/longarina-secretaria-a.webp`, `${imageRoot}/longarina-secretaria-b.webp`],
    sortOrder: 221,
  }),
  chair({
    id: "prod-set26-longarina-strike",
    slug: "longarina-strike-tres-lugares-preta",
    name: "Longarina Strike 3 Lugares Preta",
    eyebrow: "Uso coletivo",
    shortDescription: "Três assentos em polipropileno para recepções e áreas de espera.",
    description: "Longarina de três lugares com assentos e encostos em polipropileno perfurado e estrutura metálica. Consulte medidas e disponibilidade.",
    categoryId: "cat-escritorio",
    searchTerms: "longarina strike três 3 lugares polipropileno perfurada recepção espera",
    features: ["Três lugares", "Assentos em polipropileno", "Estrutura metálica"],
    images: [`${imageRoot}/longarina-strike.webp`],
    sortOrder: 222,
  }),
  chair({
    id: "prod-set26-presidente-tela-premium",
    slug: "cadeira-presidente-tela-premium",
    name: "Cadeira Presidente em Tela Premium",
    eyebrow: "Apoio completo",
    shortDescription: "Encosto alto em tela, apoio de cabeça e base cromada para uso executivo.",
    description: "Cadeira presidente giratória com encosto alto em tela, apoio de cabeça, suporte lombar, braços e base cromada com rodízios. Consulte as regulagens do modelo.",
    categoryId: "cat-presidente",
    searchTerms: "cadeira presidente tela premium apoio cabeça lombar base cromada escritório",
    features: ["Encosto alto em tela", "Apoio de cabeça e lombar", "Base cromada com rodízios"],
    images: [`${imageRoot}/presidente-tela-premium.webp`],
    sortOrder: 223,
  }),
  chair({
    id: "prod-set26-executiva-giratoria-sem-bracos",
    slug: "cadeira-executiva-giratoria-sem-bracos-preta",
    name: "Cadeira Executiva Giratória sem Braços",
    eyebrow: "Mobilidade compacta",
    shortDescription: "Assento e encosto estofados em um modelo compacto para postos operacionais.",
    description: "Cadeira executiva giratória sem braços, com assento e encosto estofados, regulagem de altura e base com rodízios. Consulte medidas e disponibilidade.",
    categoryId: "cat-executiva",
    searchTerms: "cadeira executiva giratória preta sem braços operacional escritório",
    features: ["Modelo sem braços", "Regulagem de altura", "Base giratória com rodízios"],
    images: [`${imageRoot}/executiva-giratoria-sem-bracos.webp`],
    sortOrder: 224,
  }),
];
